### ISSUE TITLE
Rendering of Large actions.html is too Slow

### ISSUE THREAD

**Issue by jojonas** [pfirsich/Frontdown#13]
Probably we want to pre-render the HTML table instead of parsing the JSON content.
Maybe we can also hide the "hardlink" entries (in hardlink mode) since they basically are NOP.

**Comment by pfirsich** [comment]
Fixed this (including filters for excluding actions from the html file) in commit [ae32a74](https://github.com/pfirsich/Frontdown/commit/ae32a74812b282100cb533e817a904e359c08b30)
